### ISSUE TITLE
Criar ECB do caso de uso 'Consultar velocidade ideal'

### ISSUE THREAD

**Issue by ThaineAbich** [kilaG/GpsInteligente#15]

**Comment by marcelofritz85** [comment]
Atualizado pacote de projeto do Astah com diagrama de classes de análise e diagrama de classes de projeto do caso de uso 'Consultar velocidade Ideal'.

**Comment by marcelofritz85** [comment]
O diagrama ECB atualizado esta no diretorio Demo1 do github com nome de issue #20 pois foi editado o nome.
