### ISSUE TITLE
Criar o diagrama de casos uso 

### ISSUE THREAD

**Issue by marcelofritz85** [kilaG/GpsInteligente#3]
Passar a foto do diagrama de casos de uso para documento do Astah.

**Comment by ThaineAbich** [comment]
![usecase diagram0](https://cloud.githubusercontent.com/assets/12100497/7653339/647f5036-faeb-11e4-9087-c1bed9f09637.jpg)

**Comment by ThaineAbich** [comment]
Diagrama adicionado a este ticket com sucesso. Este ticket está sendo fechado.
