### ISSUE TITLE
Editar ticket 26.

### ISSUE THREAD

**Issue by ThaineAbich** [kilaG/GpsInteligente#30]
Incluir na tela demonstrativa a informação de diferença entre a velocidade atual e ideal. Ex.: Atual:55;
Ideal:60; +5.

**Comment by marcelofritz85** [comment]
Adicionado painel na tela com informação da diferença de velocidade.

**Comment by marcelofritz85** [comment]
Adicionado documento no diretório Demo 2 demonstrando o painel de diferença de velocidade na tela.
