### ISSUE TITLE
Identificar cenários do caso de uso 'Consultar velocidade Ideal'

### ISSUE THREAD

**Issue by marcelofritz85** [kilaG/GpsInteligente#5]
Identificar cenários para poder dividir tarefas do caso de uso para o grupo.

**Comment by ThaineAbich** [comment]
Em atendimento.

**Comment by ThaineAbich** [comment]
Cenário 1: O Motorista escolhe a opção de Consultar a velocidade ideal clicando no botão 'Modo Inteligente' e aguarda leitura.

**Comment by ThaineAbich** [comment]
Fechando o ticket, cenário possível descrito acima.
